### ISSUE TITLE
Config and chess.js

### ISSUE THREAD

**Issue by Bekopp** [victorocna/next-chessground#1]
Great wrapper :+1: 

Can you provide some configuration examples and chess.js integration? 

Thanks!

**Comment by victorocna** [comment]
Thank you very much!

Sure thing, I'll write some documentation right now.

Cheers :+1:

**Comment by victorocna** [comment]
In the process of writing the docs I have discovered that the package is not that configurable (yet). Would you like to bring your own board and pieces as component props?

**Comment by Bekopp** [comment]
I experimented that we can use the examples in [chessground-examples](https://github.com/ornicar/chessground-examples) repositories. The examples are working fine inside this wrapper out of the box as described in [README](https://github.com/chesscoders/next-chessground/blob/master/README.md). If one uses .js/.jsx, the "Type"script has to be removed or else, your IDE will shout. Config as in [chessground documentation](https://github.com/ornicar/chessground#documentation).

**Comment by Bekopp** [comment]
Oh, I didn't refresh my browser. I only saw your reply after I commented and closed this issue. I'm now reopen this issue and let you decide.

BTW, which parts that you discovered the package is not that configurable (yet)? Part of bringing own board and pieces as component props?

**Comment by victorocna** [comment]
Started working again on this project a couple of days ago: I decided to make this package as configurable as possible. That means that you can customize the chess pieces, the chess board, move sounds and others straight from the chess board (it now has a settings icon in the right hand side of the board).

I will add some examples shortly.

**Comment by victorocna** [comment]
https://next-chessground.vercel.app/
